"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  onCursorPos: (callback) =>
    ipcRenderer.on("cursor-pos", (_evt, data) => callback(data)),
  onKeyPressed: (callback) =>
    ipcRenderer.on("key-pressed", () => callback()),
  onMouseWheel: (callback) =>
    ipcRenderer.on("mouse-wheel", (_evt, event) => callback(event)),
  onDoStretch: (callback) =>
    ipcRenderer.on("do-stretch", () => callback()),
  onDoJump: (callback) =>
    ipcRenderer.on("do-jump", () => callback()),
  onShareRecord: (callback) =>
    ipcRenderer.on("share-record", () => callback()),
  onShareCaptureCancel: (callback) =>
    ipcRenderer.on("share-capture-cancel", () => callback()),
  onCatNameEdit: (callback) =>
    ipcRenderer.on("cat-name-edit", (_evt, name) => callback(name)),
  onCatNameChanged: (callback) =>
    ipcRenderer.on("cat-name-changed", (_evt, settings) => callback(settings)),
  onAiTaskComplete: (callback) =>
    ipcRenderer.on("ai-task-complete", (_evt, event) => callback(event)),
  onAiTaskState: (callback) =>
    ipcRenderer.on("ai-task-state", (_evt, event) => callback(event)),
  onAiTaskNotification: (callback) =>
    ipcRenderer.on("ai-task-notification", (_evt, event) => callback(event)),
  remindersGet: () => ipcRenderer.invoke("reminders-get"),
  reminderAdd: (payload) => ipcRenderer.invoke("reminder-add", payload),
  reminderUpdate: (payload) => ipcRenderer.invoke("reminder-update", payload),
  reminderDelete: (id) => ipcRenderer.invoke("reminder-delete", id),
  reminderEnabledSet: (payload) => ipcRenderer.invoke("reminder-enabled-set", payload),
  onRemindersChanged: (callback) =>
    ipcRenderer.on("reminders-changed", (_evt, reminders) => callback(reminders)),
  onReminderTriggered: (callback) =>
    ipcRenderer.on("reminder-triggered", (_evt, payload) => callback(payload)),
  onReminderPanelOpen: (callback) =>
    ipcRenderer.on("reminder-panel-open", () => callback()),
  onReminderSettingsChanged: (callback) =>
    ipcRenderer.on("reminder-settings-changed", (_evt, settings) => callback(settings)),
  pomodoroGet: () => ipcRenderer.invoke("pomodoro-get"),
  pomodoroStart: () => ipcRenderer.invoke("pomodoro-start"),
  pomodoroPause: () => ipcRenderer.invoke("pomodoro-pause"),
  pomodoroReset: () => ipcRenderer.invoke("pomodoro-reset"),
  pomodoroFocusSet: (min) => ipcRenderer.invoke("pomodoro-focus-set", min),
  onPomodoroFocusEdit: (callback) =>
    ipcRenderer.on("pomodoro-focus-edit", (_evt, min) => callback(min)),
  onPomodoroState: (callback) =>
    ipcRenderer.on("pomodoro-state", (_evt, state) => callback(state)),
  onPomodoroComplete: (callback) =>
    ipcRenderer.on("pomodoro-complete", (_evt, state) => callback(state)),
  onPomodoroFocusStart: (callback) =>
    ipcRenderer.on("pomodoro-focus-start", () => callback()),
  onUpdateState: (callback) =>
    ipcRenderer.on("update-state", (_evt, state) => callback(state)),
  onTaskCompleteSoundVolume: (callback) =>
    ipcRenderer.on("task-complete-sound-volume", (_evt, volume) => callback(volume)),
  updateCheck: () => ipcRenderer.invoke("update-check"),
  updateDownload: () => ipcRenderer.invoke("update-download"),
  updateInstall: () => ipcRenderer.invoke("update-install"),
  dragWindow: (dx, dy) => ipcRenderer.send("drag-window", dx, dy),
  dragWindowEnded: () => ipcRenderer.send("drag-window-ended"),
  setMouseEventsEnabled: (enabled) => ipcRenderer.send("set-mouse-events-enabled", enabled),
  showContextMenu: () => ipcRenderer.send("show-context-menu"),
  setStretchMode: (enabled) => ipcRenderer.send("set-stretch-mode", enabled),
  setHuntingMode: (enabled) => ipcRenderer.send("set-hunting-mode", enabled),
  shareCaptureOptions: (options) => ipcRenderer.invoke("share-capture-options", options),
  shareCaptureStarted: () => ipcRenderer.invoke("share-capture-started"),
  shareCaptureOverlayHide: () => ipcRenderer.invoke("share-capture-overlay-hide"),
  shareVideoSave: (payload) => ipcRenderer.invoke("share-video-save", payload),
  shareErrorDialog: (message) => ipcRenderer.invoke("share-error-dialog", message),
  userNameGet: () => ipcRenderer.invoke("user-name-get"),
  userNameSet: (name) => ipcRenderer.invoke("user-name-set", name),
  onUserNameEdit: (callback) =>
    ipcRenderer.on("user-name-edit", (_evt, name) => callback(name)),
  onUserNameChanged: (callback) =>
    ipcRenderer.on("user-name-changed", (_evt, settings) => callback(settings)),
  catNameGet: () => ipcRenderer.invoke("cat-name-get"),
  catNameSet: (name) => ipcRenderer.invoke("cat-name-set", name),
  catNameVisibleSet: (visible) => ipcRenderer.invoke("cat-name-visible-set", visible),
  fixedMessageGet: () => ipcRenderer.invoke("fixed-message-get"),
  fixedMessageSet: (message) => ipcRenderer.invoke("fixed-message-set", message),
  onFixedMessageEdit: (callback) =>
    ipcRenderer.on("fixed-message-edit", (_evt, message) => callback(message)),
  onFixedMessageChanged: (callback) =>
    ipcRenderer.on("fixed-message-changed", (_evt, settings) => callback(settings)),
  catNamePromptShown: () => ipcRenderer.invoke("cat-name-prompt-shown"),
  taskCompleteSoundVolumeGet: () => ipcRenderer.invoke("task-complete-sound-volume-get"),
  taskCompleteSoundVolumeSet: (volume) => ipcRenderer.invoke("task-complete-sound-volume-set", volume),

  // 패턴 (펫 + 에디터 양쪽에서 사용)
  patternGet: () => ipcRenderer.invoke("pattern-get"),
  patternSet: (pattern) => ipcRenderer.send("pattern-set", pattern),
  patternPresetsGet: () => ipcRenderer.invoke("pattern-presets-get"),
  patternCustomPresetSave: (payload) => ipcRenderer.invoke("pattern-custom-preset-save", payload),
  patternCustomPresetDelete: (id) => ipcRenderer.invoke("pattern-custom-preset-delete", id),
  patternCustomPresetRename: (payload) => ipcRenderer.invoke("pattern-custom-preset-rename", payload),
  patternCustomPresetsExport: (id) => ipcRenderer.invoke("pattern-custom-presets-export", id),
  patternCustomPresetsImport: () => ipcRenderer.invoke("pattern-custom-presets-import"),
  patternConfirmClearAll: (message) => ipcRenderer.invoke("pattern-confirm-clear-all", message),
  patternConfirmDeletePreset: (message) => ipcRenderer.invoke("pattern-confirm-delete-preset", message),
  patternConfirmDiscardChanges: (message) => ipcRenderer.invoke("pattern-confirm-discard-changes", message),
  onPatternChanged: (callback) =>
    ipcRenderer.on("pattern-changed", (_evt, p) => callback(p)),
  openPatternEditor: () => ipcRenderer.send("open-pattern-editor"),
  openMappingEditor: () => ipcRenderer.send("open-mapping-editor"),
  mappingLoad: () => ipcRenderer.invoke("mapping-load"),
  mappingSave: (mappings) => ipcRenderer.invoke("mapping-save", mappings),
  svgLoad: (svgName) => ipcRenderer.invoke("svg-load", svgName),

  licenseActivate: (licenseKey) => ipcRenderer.invoke("license-activate", licenseKey),
  licenseCurrent: () => ipcRenderer.invoke("license-current"),
  onLicenseError: (callback) =>
    ipcRenderer.on("license-error", (_evt, message) => callback(message)),
  languageGet: () => ipcRenderer.invoke("language-get"),
  languageSet: (language) => ipcRenderer.invoke("language-set", language),
  onLanguageChanged: (callback) =>
    ipcRenderer.on("language-changed", (_evt, language) => callback(language)),
});
